### ISSUE TITLE
¿Ayuda con PEC4?

### ISSUE THREAD

**Issue by martamorata** [sebastianflor/practica4#1]
¡Hola! 😊 Soy una chica estudiante de la UNED en primero de ing. informática, he estado mirando tu trabajo del año pasado y la verdad que me ha servido mucho para coger ideas e inspirarme, pero aún así me está costando mucho realizar la cuarta PEC de este año😔, ¿Estarías interesado en darme clases particulares (cobrando la cantidad que veas más conveniente) para ayudarme con la práctica? Muchas gracias por tomarte el tiempo de leerme, un saludo 🥰.

**Comment by jsflor** [comment]
Buenas @martamorata contáctame por [email](mailto:sebastian-flor@hotmail.com) o Telegram ("@sebasf97")
